name: crm
description: Nanosoft's Mobile CRM
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.6
  uuid: ^3.0.6
  dartz: ^0.10.1
  flutter_hooks: ^0.18.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_hooks_test: ^0.0.2
  mocktail: ^0.3.0
  build_runner: ^2.3.0
flutter:
  uses-material-design: true
